### ISSUE TITLE
authy function is undefined

### ISSUE THREAD

**Issue by ardnor** [srmklive/laravel-2fa-demo#8]
Hi,

I am using laravel 5.4 and error occured below after registering and redirected to home route.

(1/1) FatalThrowableErrorCall to undefined function App\Http\Controllers\authy()
--

in HomeController.php (line 26)

Please check your package because it seems authy() is not readable as authy class.

Thanks.

**Comment by srmklive** [comment]
Kindly open a PR for this in 5.4 branch.
